### PR TITLE
BI-1821 - Experiment import/download buttons wrong color

### PR DESCRIPTION
**Pull request by nickpalladino**
# Description
**Story:** [BI-1821](https://breedinginsight.atlassian.net/browse/BI-1821?atlOrigin=eyJpIjoiNDRjODQ5MDZmNTQ3NDhkMjk3M2M1MmU4NjFkNWI1MDQiLCJwIjoiaiJ9)

- Added action menu component and replaced buttons with it on Experiment page
- Refactored ExperimentObservationsDownloadButton so that activation is outside the component and has dynamic reloading of study options and renamed to modal
- Refactored ExperimentObservationsTable so that there is one modal rather than one for each row in the table

# Dependencies
- develop on bi-api

# Testing
- Ensure download links in ExperimentObservationsTable work as before
- Ensure action menu items work as expected

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

[BI-1821]: https://breedinginsight.atlassian.net/browse/BI-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mlm483** [comment]
Running TAF to be safe: https://github.com/Breeding-Insight/taf/actions/runs/5955738878.

**Review by mlm483 — COMMENTED** [review]
Looks good!

Unfortunately it looks like it'll require some manual merge conflict resolution.
I'd like to re-test once you merge in develop if that's alright.

**Comment by nickpalladino** [comment]
> Looks good!
> 
> Unfortunately it looks like it'll require some manual merge conflict resolution. I'd like to re-test once you merge in develop if that's alright.

Merged in develop

**Comment by nickpalladino** [comment]
> Running TAF to be safe: https://github.com/Breeding-Insight/taf/actions/runs/5955738878.

Looks like there is a failing step but seems odd because it's mentioning a file, may have to look into it more

**Review by dmeidlin — APPROVED** [review]

**Comment by mlm483** [comment]
> Running TAF to be safe: https://github.com/Breeding-Insight/taf/actions/runs/5955738878.

BTW TAF looks good, the only failure is a known issue that's fixed by this PR: https://github.com/Breeding-Insight/bi-docker-stack/pull/27

**Review by mlm483 — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
