### PR TITLE
[BI-677] - Connect PUT traits to back end

### PR DESCRIPTION
**Pull request by ctucker3**
Hook up the PUT traits on the front end to the backend. 

See other PRs:
https://github.com/Breeding-Insight/bi-api/pull/68
https://github.com/Breeding-Insight/sgn/pull/7

### CODE REVIEW

**Review by nickpalladino — COMMENTED** [review]
Was playing around editing traits and when I switched from text to ordinal I get a 422 error. Looks like bi-web is not sending categories in the scale info.

image

**Review by timparsons — APPROVED** [review]
Approving contingent on addressing the comment Nick made earlier about the `422`.

**Comment by ctucker3** [comment]
> Was playing around editing traits and when I switched from text to ordinal I get a 422 error. Looks like bi-web is not sending categories in the scale info.
> 
> image

Good catch! Vue wasn't catching the array update.

**Review by nickpalladino — COMMENTED** [review]
The text -> ordinal thing works but I'm seeing some other things on the edit form, maybe we just create a new card to fix bugs with the form? If I try to edit and change from ordinal to nominal, it doesn't seem to change.

**Comment by ctucker3** [comment]
> The text -> ordinal thing works but I'm seeing some other things on the edit form, maybe we just create a new card to fix bugs with the form? If I try to edit and change from ordinal to nominal, it doesn't seem to change.

Yeah I like that idea. Made a card fir it:

https://breedinginsight.atlassian.net/browse/BI-735

**Review by nickpalladino — APPROVED** [review]

**Pull request merged**
