### PR TITLE
BI-674 - Program Definable BrAPI Service URL

### PR DESCRIPTION
**Pull request by nickpalladino**
## Changes
- Added brapi URL input to program creation form
- Populated numUsers column in programs table
- Added brapiUrl to programs table

## Notes
- There are corresponding cards in bi-api and sgn

### CODE REVIEW

**Review by timparsons — APPROVED** [review]
Looks good!

**Comment by DebWeigand** [comment]
rather than the verbiage next to the checkbox "Specify custom program data storage location", in order to satisfy the first acceptance scenario, would it be beneficial for the text to read "Specify custom program data storage location, otherwise default will be used"?
And, would it be beneficial to spell out the default location?

**Comment by nickpalladino** [comment]
> rather than the verbiage next to the checkbox "Specify custom program data storage location", in order to satisfy the first acceptance scenario, would it be beneficial for the text to read "Specify custom program data storage location, otherwise default will be used"?
> And, would it be beneficial to spell out the default location?

I see what you're saying with the description but to me it reads more cleanly to have the checkbox label be more yes/no. After talking with Tim I updated the acceptance criteria to not specify what the default location is because there was implementation implications that didn't seem worth it. Not sure how others feel?

**Comment by ctucker3** [comment]
Two UI things:

screencapture-localhost-8080-admin-program-management-2021-02-22-11_07_09

Can you add some space between the label and the checkbox? Like an `ml-2` or something? It looks cramped. 

Also, in the help text, and in the error message for a poorly formatted url can you put an example of what a properly formatted url looks like?

**Review by ctucker3 — CHANGES_REQUESTED** [review]
See comment on UI above.

**Review by ctucker3 — APPROVED** [review]

**Review by DebWeigand — APPROVED** [review]

**Comment by nickpalladino** [comment]
> Two UI things:
> 
> screencapture-localhost-8080-admin-program-management-2021-02-22-11_07_44
> 
> Can you add some space between the label and the checkbox? Like an `ml-2` or something? It looks cramped.

I wrapped the input in a label and in browser that added some more space, does it look good on yours?

> Also, in the help text, and in the error message for a poorly formatted url can you put an example of what a properly formatted url looks like?

I added an example url to the help text, seems the validation message is automatically generated.

**Pull request merged**
